"""Support JSON structure

Revision ID: d01255c983a3
Revises: 0c200c1447d9
Create Date: 2026-03-30 17:16:12.002569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd01255c983a3'
down_revision = '0c200c1447d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sahal_service_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('json_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['json_id'])

    with op.batch_alter_table('sahal_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('json_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('base_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.create_unique_constraint(None, ['json_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sahal_services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('base_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.drop_column('json_id')

    with op.batch_alter_table('sahal_service_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('json_id')

    # ### end Alembic commands ###
